function getData() {
  const data = [
    {
      name: 'Bamboo Straw',
      price: 1.8,
      discount: 30,
      description: 'wooden, eco-friendly straw',
      collection: 'straws',
      img: '1 bowl.jpg',
      inStock: 100,
      vendor: 'BambooCo',
      isSet: false,
      size: null,
      piecesInSet: null,
    },
    {
      name: 'Bamboo Straw Set',
      price: 16,
      discount: 10,
      description: 'wooden, eco-friendly straw set',
      collection: 'straws',
      img: '2 bowl.jpg',
      inStock: 100,
      vendor: 'BambooCo',
      isSet: true,
      size: null,
      piecesInSet: 10,
    },
    {
      name: 'Coconut Bowl',
      price: 12.95,
      discount: 20,
      description: 'wooden, eco-friendly bowl',
      collection: 'bowls',
      img: '4 bowl.jpg',
      inStock: 50,
      vendor: 'PalmTree',
      isSet: false,
      size: null,
      piecesInSet: null,
    },
    {
      name: 'Coconut Bowl Set',
      price: 12.95,
      discount: 20,
      description: 'wooden, eco-friendly bowl',
      collection: 'bowls',
      img: '4 bowl.jpg',
      inStock: 50,
      vendor: 'PalmTree',
      isSet: true,
      size: null,
      piecesInSet: 4,
    },
    {
      name: 'Coconut Bowl Set',
      price: 20.95,
      discount: 20,
      description: 'wooden, eco-friendly bowl',
      collection: 'bowls',
      img: '2 bowl.jpg',
      inStock: 50,
      vendor: 'PalmTree',
      isSet: true,
      size: null,
      piecesInSet: 2,
    },
    {
      name: 'Coconut Bowl Set',
      price: 37.95,
      discount: 20,
      description: 'wooden, eco-friendly bowl',
      collection: 'bowls',
      img: '2 bowl.jpg',
      inStock: 50,
      vendor: 'PalmTree',
      isSet: true,
      size: null,
      piecesInSet: 16,
    },
  ];

  return data;
}

module.exports = getData;
